### PR TITLE
feat: bump deps to prevent security warning

### PR DESCRIPTION
**Pull request by damianmr**
https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v4.6.1

Prevents these warnings:

image

### CODE REVIEW

**Comment by damianmr** [comment]
@andresmatasuarez any particular reason you could think of that would explain the reason to remove so many packages in package-lock.json? I just ran npm install.

**Comment by andresmatasuarez** [comment]
mmm haven't got the slightest idea, I noticed the whole red diff is just the removal of the property `packages` in the package-lock file, while the `dependencies` property doesn't change a bit

I noticed `packages` & `dependencies` both exist in npm v7: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#packages

But only `dependencies` is present in npm v6: https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json#file-format

could you confirm which npm version did you use?

**Comment by damianmr** [comment]
Great, I re-ran it using npm 7 and now the diff is much smaller.

**Comment by damianmr** [comment]
@andresmatasuarez let me know if we can merge

**Comment by andresmatasuarez** [comment]
would it make sense to also include the `engine` properties in `package.json` that @quackware added in some of the other repos?

```json
"engines": {
    "npm": ">= 7.17.0",
    "node": ">= 14.17.3"
  }
```

and `engine-strict=true` in `.npmrc`

**Comment by damianmr** [comment]
I don't know, this isn't expected to run on local computers anyway! 

According [this](https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html) without the `engineStrict` property, those are mostly hints anyway

**Comment by andresmatasuarez** [comment]
yeap, you're right! we aren't running them on our machines, so go ahead with the merge

**Pull request merged**
